export const tasks = [
  {
    title: 'Todo',
    tasks: [
      {
        id: Math.floor(Math.random() * 1000000),
        title: 'Task 1',
        description: 'Description 1',
        done: false,    
        date:1389878466730,
        priority:"medium",
        status: "complete",
      },
      {
        id: Math.floor(Math.random() * 1000000),
        title: 'Task 2',
        description: 'Description 2',
        date:1389878466730,
        done: false,
        priority:"medium",
        status: "complete",
      },
      {
        id: Math.floor(Math.random() * 1000000),
        title: 'Task 3',
        description: 'Description 3',
        date:1389878466730,
        done: false,
        priority:"medium",
        status: "complete",
      },
    ],
  },
  {
    title: 'In Progress',
    tasks: [
      {
        id: Math.floor(Math.random() * 1000000),
        title: 'Task 1',
        description: 'Description 1',
        done: false,
        date:1389878466730,
        priority:"medium",
        status: "complete",
      },
      {
        id: Math.floor(Math.random() * 1000000),
        title: 'Task 2',
        description: 'Description 2',
        date:1389878466730,
        done: false,
        priority:"medium",
        status: "complete",
      },
      {
        id: Math.floor(Math.random() * 1000000),
        title: 'Task 3',
        description: 'Description 3',
        date:1389878466730,
        done: false,
        priority:"medium",
        status: "complete",
      },
    ],
  },
  {
    title: 'Done',
    tasks: [
      {
        id: Math.floor(Math.random() * 1000000),
        title: 'Task 1',
        description: 'Description 1',
        done: false,
        date:1389878466730,
        priority:"medium",
        status: "complete",
      },
      {
        id: Math.floor(Math.random() * 1000000),
        title: 'Task 2',
        description: 'Description 2',
        date:1389878466730,
        done: false,
        priority:"medium",
        status: "complete",
      },
      {
        id: Math.floor(Math.random() * 1000000),
        title: 'Task 3',
        description: 'Description 3',
        date:1389878466730,
        done: false,
        priority:"medium",
        status: "complete",
      },
    ],
  },
]